/*----- PROTECTED REGION ID(RA153_28StateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        RA153_28StateMachine.cpp
//
// description : State machine file for the RA153_28 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <RA153_28.h>

/*----- PROTECTED REGION END -----*/	//	RA153_28::RA153_28StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  FAULT   |  
//  MOVING  |  


namespace RA153_28_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_rPosition_allowed()
 *	Description : Execution allowed for rPosition attribute
 */
//--------------------------------------------------------
bool RA153_28::is_rPosition_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rPosition attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_28::rPositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::rPositionStateAllowed_WRITE

	//	Not any excluded states for rPosition attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::rPositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::rPositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_aPosition_allowed()
 *	Description : Execution allowed for aPosition attribute
 */
//--------------------------------------------------------
bool RA153_28::is_aPosition_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for aPosition attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_28::aPositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::aPositionStateAllowed_WRITE

	//	Not any excluded states for aPosition attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::aPositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::aPositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_rZeroPosition_allowed()
 *	Description : Execution allowed for rZeroPosition attribute
 */
//--------------------------------------------------------
bool RA153_28::is_rZeroPosition_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rZeroPosition attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_28::rZeroPositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::rZeroPositionStateAllowed_WRITE

	//	Not any excluded states for rZeroPosition attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::rZeroPositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::rZeroPositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_LeftEnd_allowed()
 *	Description : Execution allowed for LeftEnd attribute
 */
//--------------------------------------------------------
bool RA153_28::is_LeftEnd_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LeftEnd attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::LeftEndStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::LeftEndStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_CentralEnd_allowed()
 *	Description : Execution allowed for CentralEnd attribute
 */
//--------------------------------------------------------
bool RA153_28::is_CentralEnd_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CentralEnd attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::CentralEndStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::CentralEndStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_RightEnd_allowed()
 *	Description : Execution allowed for RightEnd attribute
 */
//--------------------------------------------------------
bool RA153_28::is_RightEnd_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for RightEnd attribute in read access.
	/*----- PROTECTED REGION ID(RA153_28::RightEndStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::RightEndStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : RA153_28::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool RA153_28::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(RA153_28::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_28::StopStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(RA153_28::RA153_28StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	RA153_28::RA153_28StateAllowed.AdditionalMethods

}	//	End of namespace
