/*----- PROTECTED REGION ID(MonitorClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        MonitorClass.cpp
//
// description : C++ source for the MonitorClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Monitor once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MonitorClass.h>

/*----- PROTECTED REGION END -----*/	//	MonitorClass.cpp

//-------------------------------------------------------------------
/**
 *	Create MonitorClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Monitor_class(const char *name) {
		return Monitor_ns::MonitorClass::init(name);
	}
}

namespace Monitor_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
MonitorClass *MonitorClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		MonitorClass::MonitorClass(string &s)
 * description : 	constructor for the MonitorClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
MonitorClass::MonitorClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering MonitorClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(MonitorClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::constructor

	cout2 << "Leaving MonitorClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		MonitorClass::~MonitorClass()
 * description : 	destructor for the MonitorClass
 */
//--------------------------------------------------------
MonitorClass::~MonitorClass()
{
	/*----- PROTECTED REGION ID(MonitorClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		MonitorClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
MonitorClass *MonitorClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new MonitorClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		MonitorClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
MonitorClass *MonitorClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartCountClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartCountClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartCountClass::execute(): arrived" << endl;
	((static_cast<Monitor *>(device))->start_count());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopCountClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopCountClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopCountClass::execute(): arrived" << endl;
	((static_cast<Monitor *>(device))->stop_count());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetCounterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetCounterClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetCounterClass::execute(): arrived" << endl;
	((static_cast<Monitor *>(device))->reset_counter());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : MonitorClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum MonitorClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MonitorClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum MonitorClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MonitorClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum MonitorClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : MonitorClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void MonitorClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "Device";
	prop_desc = "path to device";
	prop_def  = "/dev/plxdev1";
	vect_data.clear();
	vect_data.push_back("/dev/plxdev1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "channel";
	prop_desc = "channel of counter\nnote: timer settings for all 4 channels";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : MonitorClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void MonitorClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : MonitorClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void MonitorClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(MonitorClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Monitor(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Monitor *dev = static_cast<Monitor *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(MonitorClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MonitorClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void MonitorClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(MonitorClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::attribute_factory_before
	//	Attribute : Count
	CountAttrib	*count = new CountAttrib();
	Tango::UserDefaultAttrProp	count_prop;
	//	description	not set for Count
	//	label	not set for Count
	//	unit	not set for Count
	//	standard_unit	not set for Count
	//	display_unit	not set for Count
	//	format	not set for Count
	//	max_value	not set for Count
	//	min_value	not set for Count
	//	max_alarm	not set for Count
	//	min_alarm	not set for Count
	//	max_warning	not set for Count
	//	min_warning	not set for Count
	//	delta_t	not set for Count
	//	delta_val	not set for Count
	
	count->set_default_properties(count_prop);
	//	Not Polled
	count->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(count);

	//	Attribute : TimeInterval
	TimeIntervalAttrib	*timeinterval = new TimeIntervalAttrib();
	Tango::UserDefaultAttrProp	timeinterval_prop;
	timeinterval_prop.set_description("Time interval in ms");
	timeinterval_prop.set_label("Time interval");
	timeinterval_prop.set_unit("ms");
	//	standard_unit	not set for TimeInterval
	//	display_unit	not set for TimeInterval
	//	format	not set for TimeInterval
	//	max_value	not set for TimeInterval
	//	min_value	not set for TimeInterval
	//	max_alarm	not set for TimeInterval
	//	min_alarm	not set for TimeInterval
	//	max_warning	not set for TimeInterval
	//	min_warning	not set for TimeInterval
	//	delta_t	not set for TimeInterval
	//	delta_val	not set for TimeInterval
	
	timeinterval->set_default_properties(timeinterval_prop);
	//	Not Polled
	timeinterval->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(timeinterval);

	//	Attribute : Complete
	CompleteAttrib	*complete = new CompleteAttrib();
	Tango::UserDefaultAttrProp	complete_prop;
	//	description	not set for Complete
	//	label	not set for Complete
	//	unit	not set for Complete
	//	standard_unit	not set for Complete
	//	display_unit	not set for Complete
	//	format	not set for Complete
	//	max_value	not set for Complete
	//	min_value	not set for Complete
	//	max_alarm	not set for Complete
	//	min_alarm	not set for Complete
	//	max_warning	not set for Complete
	//	min_warning	not set for Complete
	//	delta_t	not set for Complete
	//	delta_val	not set for Complete
	
	complete->set_default_properties(complete_prop);
	complete->set_polling_period(1000);
	complete->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(complete);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(MonitorClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MonitorClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void MonitorClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(MonitorClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::pipe_factory_before
	/*----- PROTECTED REGION ID(MonitorClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MonitorClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void MonitorClass::command_factory()
{
	/*----- PROTECTED REGION ID(MonitorClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::command_factory_before


	//	Command StartCount
	StartCountClass	*pStartCountCmd =
		new StartCountClass("StartCount",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCountCmd);

	//	Command StopCount
	StopCountClass	*pStopCountCmd =
		new StopCountClass("StopCount",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCountCmd);

	//	Command ResetCounter
	ResetCounterClass	*pResetCounterCmd =
		new ResetCounterClass("ResetCounter",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCounterCmd);

	/*----- PROTECTED REGION ID(MonitorClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		MonitorClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void MonitorClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(MonitorClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		MonitorClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void MonitorClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Monitor *dev = static_cast<Monitor *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(MonitorClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : MonitorClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *MonitorClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(MonitorClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	MonitorClass::Additional Methods
} //	namespace
