/*----- PROTECTED REGION ID(Monitor.h) ENABLED START -----*/
//=============================================================================
//
// file :        Monitor.h
//
// description : Include file for the Monitor class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Monitor_H
#define Monitor_H

#include <tango.h>

#include "Counter.h"

/*----- PROTECTED REGION END -----*/	//	Monitor.h

/**
 *  Monitor class description:
 *    
 */

namespace Monitor_ns
{
/*----- PROTECTED REGION ID(Monitor::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Monitor::Additional Class Declarations

class Monitor : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Monitor::Data Members) ENABLED START -----*/

public:
	Counter *cr;

/*----- PROTECTED REGION END -----*/	//	Monitor::Data Members

//	Device property data members
public:
	//	Device:	path to device
	string	device;
	//	channel:	channel of counter
	//  note: timer settings for all 4 channels
	Tango::DevShort	channel;

//	Attribute data members
public:
	Tango::DevULong	*attr_Count_read;
	Tango::DevBoolean	*attr_Complete_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Monitor(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Monitor(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Monitor(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~Monitor() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Monitor::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : Monitor::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Count related methods
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void read_Count(Tango::Attribute &attr);
	virtual bool is_Count_allowed(Tango::AttReqType type);
/**
 *	Attribute TimeInterval related methods
 *	Description: Time interval in ms
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void write_TimeInterval(Tango::WAttribute &attr);
	virtual bool is_TimeInterval_allowed(Tango::AttReqType type);
/**
 *	Attribute Complete related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_Complete(Tango::Attribute &attr);
	virtual bool is_Complete_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Monitor::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command StartCount related method
	 *	Description: 
	 *
	 */
	virtual void start_count();
	virtual bool is_StartCount_allowed(const CORBA::Any &any);
	/**
	 *	Command StopCount related method
	 *	Description: 
	 *
	 */
	virtual void stop_count();
	virtual bool is_StopCount_allowed(const CORBA::Any &any);
	/**
	 *	Command ResetCounter related method
	 *	Description: Reset Counter and Timer
	 *
	 */
	virtual void reset_counter();
	virtual bool is_ResetCounter_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : Monitor::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Monitor::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Monitor::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Monitor::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Monitor::Additional Classes Definitions

}	//	End of namespace

#endif   //	Monitor_H
