/*----- PROTECTED REGION ID(Monitor.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Monitor.cpp
//
// description : C++ source for the Monitor class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Monitor are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Monitor.h>
#include <MonitorClass.h>

/*----- PROTECTED REGION END -----*/	//	Monitor.cpp

/**
 *  Monitor class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  StartCount    |  start_count
//  StopCount     |  stop_count
//  ResetCounter  |  reset_counter
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Count         |  Tango::DevULong	Scalar
//  TimeInterval  |  Tango::DevLong	Scalar
//  Complete      |  Tango::DevBoolean	Scalar
//================================================================

namespace Monitor_ns
{
/*----- PROTECTED REGION ID(Monitor::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Monitor::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Monitor::Monitor()
 *	Description : Constructors for a Tango device
 *                implementing the classMonitor
 */
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Monitor::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_1
}
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(Monitor::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_2
}
//--------------------------------------------------------
Monitor::Monitor(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(Monitor::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Monitor::delete_device()
{
	DEBUG_STREAM << "Monitor::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::delete_device) ENABLED START -----*/
	
	delete cr;
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::delete_device
	delete[] attr_Count_read;
	delete[] attr_Complete_read;
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Monitor::init_device()
{
	DEBUG_STREAM << "Monitor::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_Count_read = new Tango::DevULong[1];
	attr_Complete_read = new Tango::DevBoolean[1];
	/*----- PROTECTED REGION ID(Monitor::init_device) ENABLED START -----*/
	
	cr = new Counter(device);
	if(cr->status < 0){
		device_state = Tango::FAULT;
		switch(cr->status){
			case COUNTER_STATUS_ERROR_FILE_DESCRIPTOR:
				device_status = "Device " + device + " is fault. =(\n";
				break;
			case COUNTER_STATUS_NOT_COUNTER_DEVICE:
				device_status = "This is not counter device! =(\n";
				break;
		}
		return;
	}
	device_state = Tango::ON;
	device_status = "device " + device + " is open. =)\n";

	/*----- PROTECTED REGION END -----*/	//	Monitor::init_device
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void Monitor::get_device_property()
{
	/*----- PROTECTED REGION ID(Monitor::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("Device"));
	dev_prop.push_back(Tango::DbDatum("channel"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on MonitorClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		MonitorClass	*ds_class =
			(static_cast<MonitorClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize Device from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  device;
		else {
			//	Try to initialize Device from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  device;
		}
		//	And try to extract Device value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  device;

		//	Try to initialize channel from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  channel;
		else {
			//	Try to initialize channel from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  channel;
		}
		//	And try to extract channel value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  channel;

	}

	/*----- PROTECTED REGION ID(Monitor::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Monitor::always_executed_hook()
{
	DEBUG_STREAM << "Monitor::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Monitor::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Monitor::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : Monitor::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void Monitor::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Monitor::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Count related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Monitor::read_Count(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Monitor::read_Count(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::read_Count) ENABLED START -----*/
	*attr_Count_read = 0;
	if(cr->status < 0){
		return;
	};

	/* procedure for read counts from counter */

	*attr_Count_read = cr->readCounter(channel);;

	attr.set_value(attr_Count_read);
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::read_Count
}
//--------------------------------------------------------
/**
 *	Write attribute TimeInterval related method
 *	Description: Time interval in ms
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Monitor::write_TimeInterval(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Monitor::write_TimeInterval(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Monitor::write_TimeInterval) ENABLED START -----*/

	cr->setTimeInterval(w_val);

	/*----- PROTECTED REGION END -----*/	//	Monitor::write_TimeInterval
}
//--------------------------------------------------------
/**
 *	Read attribute Complete related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Monitor::read_Complete(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Monitor::read_Complete(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Monitor::read_Complete) ENABLED START -----*/
	//	Set the attribute value

	*attr_Complete_read = !cr->testTimer();

	attr.set_value(attr_Complete_read);

	if(*attr_Complete_read) {
		device_state = Tango::ON;
		device_status = "Ok";
	}

	
	/*----- PROTECTED REGION END -----*/	//	Monitor::read_Complete
}

//--------------------------------------------------------
/**
 *	Method      : Monitor::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Monitor::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Monitor::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command StartCount related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void Monitor::start_count()
{
	DEBUG_STREAM << "Monitor::StartCount()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::start_count) ENABLED START -----*/
	
	cr->startTimer();
	device_state = Tango::MOVING;
	device_status = "Counting...";
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::start_count
}
//--------------------------------------------------------
/**
 *	Command StopCount related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void Monitor::stop_count()
{
	DEBUG_STREAM << "Monitor::StopCount()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::stop_count) ENABLED START -----*/
	
	cr->stopTimer();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::stop_count
}
//--------------------------------------------------------
/**
 *	Command ResetCounter related method
 *	Description: Reset Counter and Timer
 *
 */
//--------------------------------------------------------
void Monitor::reset_counter()
{
	DEBUG_STREAM << "Monitor::ResetCounter()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Monitor::reset_counter) ENABLED START -----*/
	
	cr->resetCounter();
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::reset_counter
}
//--------------------------------------------------------
/**
 *	Method      : Monitor::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void Monitor::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(Monitor::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	Monitor::add_dynamic_commands
}

/*----- PROTECTED REGION ID(Monitor::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Monitor::namespace_ending
} //	namespace
