/*----- PROTECTED REGION ID(MonitorClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        MonitorClass.h
//
// description : Include for the Monitor root class.
//               This class is the singleton class for
//                the Monitor device class.
//               It contains all properties and methods which the 
//               Monitor requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef MonitorClass_H
#define MonitorClass_H

#include <tango.h>
#include <Monitor.h>


/*----- PROTECTED REGION END -----*/	//	MonitorClass.h


namespace Monitor_ns
{
/*----- PROTECTED REGION ID(MonitorClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	MonitorClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Count class definition
class CountAttrib: public Tango::Attr
{
public:
	CountAttrib():Attr("Count",
			Tango::DEV_ULONG, Tango::READ) {};
	~CountAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Monitor *>(dev))->read_Count(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Monitor *>(dev))->is_Count_allowed(ty);}
};

//	Attribute TimeInterval class definition
class TimeIntervalAttrib: public Tango::Attr
{
public:
	TimeIntervalAttrib():Attr("TimeInterval",
			Tango::DEV_LONG, Tango::WRITE) {};
	~TimeIntervalAttrib() {};
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Monitor *>(dev))->write_TimeInterval(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Monitor *>(dev))->is_TimeInterval_allowed(ty);}
};

//	Attribute Complete class definition
class CompleteAttrib: public Tango::Attr
{
public:
	CompleteAttrib():Attr("Complete",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~CompleteAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Monitor *>(dev))->read_Complete(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Monitor *>(dev))->is_Complete_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command StartCount class definition
class StartCountClass : public Tango::Command
{
public:
	StartCountClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartCountClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartCountClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Monitor *>(dev))->is_StartCount_allowed(any);}
};

//	Command StopCount class definition
class StopCountClass : public Tango::Command
{
public:
	StopCountClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopCountClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopCountClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Monitor *>(dev))->is_StopCount_allowed(any);}
};

//	Command ResetCounter class definition
class ResetCounterClass : public Tango::Command
{
public:
	ResetCounterClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetCounterClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetCounterClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Monitor *>(dev))->is_ResetCounter_allowed(any);}
};


/**
 *	The MonitorClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  MonitorClass : public Tango::DeviceClass
#else
class MonitorClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(MonitorClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	MonitorClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static MonitorClass *init(const char *);
		static MonitorClass *instance();
		~MonitorClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		MonitorClass(string &);
		static MonitorClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Monitor_H
