/*----- PROTECTED REGION ID(RA153_16StateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        RA153_16StateMachine.cpp
//
// description : State machine file for the RA153_16 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi PNPI Gatchina (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <RA153_16.h>

/*----- PROTECTED REGION END -----*/	//	RA153_16::RA153_16StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace RA153_16_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : RA153_16::is_Valve_allowed()
 *	Description : Execution allowed for Valve attribute
 */
//--------------------------------------------------------
bool RA153_16::is_Valve_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Valve attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_16::ValveStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::ValveStateAllowed_WRITE

	//	Not any excluded states for Valve attribute in read access.
	/*----- PROTECTED REGION ID(RA153_16::ValveStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::ValveStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::is_rPosition_allowed()
 *	Description : Execution allowed for rPosition attribute
 */
//--------------------------------------------------------
bool RA153_16::is_rPosition_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rPosition attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_16::rPositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::rPositionStateAllowed_WRITE

	//	Not any excluded states for rPosition attribute in read access.
	/*----- PROTECTED REGION ID(RA153_16::rPositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::rPositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::is_aPosition_allowed()
 *	Description : Execution allowed for aPosition attribute
 */
//--------------------------------------------------------
bool RA153_16::is_aPosition_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for aPosition attribute in Write access.
	/*----- PROTECTED REGION ID(RA153_16::aPositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::aPositionStateAllowed_WRITE

	//	Not any excluded states for aPosition attribute in read access.
	/*----- PROTECTED REGION ID(RA153_16::aPositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::aPositionStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(RA153_16::RA153_16StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	RA153_16::RA153_16StateAllowed.AdditionalMethods

}	//	End of namespace
