/*----- PROTECTED REGION ID(RA153_16.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        RA153_16.cpp
//
// description : C++ source for the RA153_16 class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               RA153_16 are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Kirill Pshenichnyi PNPI Gatchina (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <RA153_16.h>
#include <RA153_16Class.h>
#include "SerialPort.h"

/*----- PROTECTED REGION END -----*/	//	RA153_16.cpp

/**
 *  RA153_16 class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Valve      |  Tango::DevBoolean	Scalar
//  rPosition  |  Tango::DevDouble	Scalar
//  aPosition  |  Tango::DevDouble	Scalar
//================================================================

namespace RA153_16_ns
{
/*----- PROTECTED REGION ID(RA153_16::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	RA153_16::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : RA153_16::RA153_16()
 *	Description : Constructors for a Tango device
 *                implementing the classRA153_16
 */
//--------------------------------------------------------
RA153_16::RA153_16(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(RA153_16::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::constructor_1
}
//--------------------------------------------------------
RA153_16::RA153_16(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(RA153_16::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::constructor_2
}
//--------------------------------------------------------
RA153_16::RA153_16(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(RA153_16::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void RA153_16::delete_device()
{
	DEBUG_STREAM << "RA153_16::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(RA153_16::delete_device) ENABLED START -----*/
	
	delete sp;
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::delete_device
	delete[] attr_Valve_read;
	delete[] attr_rPosition_read;
	delete[] attr_aPosition_read;
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void RA153_16::init_device()
{
	DEBUG_STREAM << "RA153_16::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(RA153_16::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_Valve_read = new Tango::DevBoolean[1];
	attr_rPosition_read = new Tango::DevDouble[1];
	attr_aPosition_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(RA153_16::init_device) ENABLED START -----*/


	if(sp==NULL) sp = new SP::SerialPort(serailPort.c_str());
	/* add realization for pneumatic */
	if(!motorOrValve) pneumo = new Pneumatics(sp,deviceAddr);


	/* add realization for motion */
	//if(motorOrValve)

	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::init_device
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void RA153_16::get_device_property()
{
	/*----- PROTECTED REGION ID(RA153_16::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("SerailPort"));
	dev_prop.push_back(Tango::DbDatum("Axis"));
	dev_prop.push_back(Tango::DbDatum("Valve"));
	dev_prop.push_back(Tango::DbDatum("MotorOrValve"));
	dev_prop.push_back(Tango::DbDatum("DeviceAddr"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on RA153_16Class to get class property
		Tango::DbDatum	def_prop, cl_prop;
		RA153_16Class	*ds_class =
			(static_cast<RA153_16Class *>(get_device_class()));
		int	i = -1;

		//	Try to initialize SerailPort from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  serailPort;
		else {
			//	Try to initialize SerailPort from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  serailPort;
		}
		//	And try to extract SerailPort value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  serailPort;

		//	Try to initialize Axis from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  axis;
		else {
			//	Try to initialize Axis from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  axis;
		}
		//	And try to extract Axis value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  axis;

		//	Try to initialize Valve from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  valve;
		else {
			//	Try to initialize Valve from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  valve;
		}
		//	And try to extract Valve value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  valve;

		//	Try to initialize MotorOrValve from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  motorOrValve;
		else {
			//	Try to initialize MotorOrValve from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  motorOrValve;
		}
		//	And try to extract MotorOrValve value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  motorOrValve;

		//	Try to initialize DeviceAddr from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  deviceAddr;
		else {
			//	Try to initialize DeviceAddr from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  deviceAddr;
		}
		//	And try to extract DeviceAddr value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  deviceAddr;

	}

	/*----- PROTECTED REGION ID(RA153_16::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void RA153_16::always_executed_hook()
{
	DEBUG_STREAM << "RA153_16::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(RA153_16::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void RA153_16::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "RA153_16::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(RA153_16::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : RA153_16::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void RA153_16::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "RA153_16::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(RA153_16::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Valve related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::read_Valve(Tango::Attribute &attr)
{
	DEBUG_STREAM << "RA153_16::read_Valve(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(RA153_16::read_Valve) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Valve_read);
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::read_Valve
}
//--------------------------------------------------------
/**
 *	Write attribute Valve related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::write_Valve(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "RA153_16::write_Valve(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(RA153_16::write_Valve) ENABLED START -----*/
	if(motorOrValve) return;

	// open valve

	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::write_Valve
}
//--------------------------------------------------------
/**
 *	Read attribute rPosition related method
 *	Description: Reletively position
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::read_rPosition(Tango::Attribute &attr)
{
	DEBUG_STREAM << "RA153_16::read_rPosition(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(RA153_16::read_rPosition) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_rPosition_read);
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::read_rPosition
}
//--------------------------------------------------------
/**
 *	Write attribute rPosition related method
 *	Description: Reletively position
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::write_rPosition(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "RA153_16::write_rPosition(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(RA153_16::write_rPosition) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::write_rPosition
}
//--------------------------------------------------------
/**
 *	Read attribute aPosition related method
 *	Description: Absolute position
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::read_aPosition(Tango::Attribute &attr)
{
	DEBUG_STREAM << "RA153_16::read_aPosition(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(RA153_16::read_aPosition) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_aPosition_read);
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::read_aPosition
}
//--------------------------------------------------------
/**
 *	Write attribute aPosition related method
 *	Description: Absolute position
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void RA153_16::write_aPosition(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "RA153_16::write_aPosition(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(RA153_16::write_aPosition) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::write_aPosition
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void RA153_16::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(RA153_16::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : RA153_16::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void RA153_16::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(RA153_16::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	RA153_16::add_dynamic_commands
}

/*----- PROTECTED REGION ID(RA153_16::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	RA153_16::namespace_ending
} //	namespace
