/*----- PROTECTED REGION ID(Pneumo.h) ENABLED START -----*/
//=============================================================================
//
// file :        Pneumo.h
//
// description : Include file for the Pneumo class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Pshenichnyi Kirill PNPI (c) 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Pneumo_H
#define Pneumo_H

#include <tango.h>

#include "SerialPort.h"
#include "Pneumatics.h"


/*----- PROTECTED REGION END -----*/	//	Pneumo.h

/**
 *  Pneumo class description:
 *    
 */

namespace Pneumo_ns
{
/*----- PROTECTED REGION ID(Pneumo::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Pneumo::Additional Class Declarations

class Pneumo : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Pneumo::Data Members) ENABLED START -----*/

public:
    SP::SerialPort *sp = NULL;
    Pneumatics *pneumo;


/*----- PROTECTED REGION END -----*/	//	Pneumo::Data Members

//	Device property data members
public:
	//	SerialPort:	Just serial port, such as ``/dev/ttyS0`` for example
	string	serialPort;
	//	DeviceAddr:	Address of device, for example ``085`` <- string!
	string	deviceAddr;
	//	NumOfValve:	Just number of valve [0..16]
	Tango::DevShort	numOfValve;

//	Attribute data members
public:
	Tango::DevBoolean	*attr_sensor_read;
	Tango::DevUShort	*attr_allsensor_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Pneumo(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Pneumo(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Pneumo(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~Pneumo() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Pneumo::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : Pneumo::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute valve related methods
 *	Description: state of valve
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void write_valve(Tango::WAttribute &attr);
	virtual bool is_valve_allowed(Tango::AttReqType type);
/**
 *	Attribute sensor related methods
 *	Description: Sensor of pressure
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_sensor(Tango::Attribute &attr);
	virtual bool is_sensor_allowed(Tango::AttReqType type);
/**
 *	Attribute allsensor related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUShort
 *	Attr type:	Scalar
 */
	virtual void read_allsensor(Tango::Attribute &attr);
	virtual bool is_allsensor_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Pneumo::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : Pneumo::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Pneumo::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Pneumo::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Pneumo::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Pneumo::Additional Classes Definitions

}	//	End of namespace

#endif   //	Pneumo_H
